Transform: AWS::Serverless-2016-10-31

# Globals:
#   set of globals

# Description:
#   String

# Metadata:
#   template metadata

Parameters:
  S3BucketName:
    Type: String


# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3BucketName

  PresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/presignedurl
      Environment:
        Variables:
          S3Bucket: !Ref UploadBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /presignedurl
            RequestParameters:
              - method.request.querystring.filename:
                  Required: true
                  Caching: false
      Handler: index.handler
      Runtime: python3.9
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 's3:PutObject'
              Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'
  
  ObjectProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/objectprocessing
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: 's3:ObjectCreated:*'
      Handler: index.handler
      Runtime: python3.9
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 's3:GetObject'
              Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'
            - Effect: Allow
              Action: 'rekognition:RecognizeCelebrities'
              Resource: '*'



# Outputs:
#   set of outputs