Transform: AWS::Serverless-2016-10-31

# Globals:
#   set of globals

# Description:
#   String

# Metadata:
#   template metadata

Parameters:
  S3BucketName:
    Type: String


# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

Resources:
  UploadBucket:
    Type: 'AWS::S3::Bucket'
    # DeletionPolicy: Retain
    Properties:
      BucketName: !Ref S3BucketName

  PresignedUrlFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: lambda/presignedurl
      Environment:
        Variables:
          S3Bucket: !Ref UploadBucket
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Method: GET
            Path: /presignedurl
            RequestParameters:
              - method.request.querystring.filename:
                  Required: true
                  Caching: false
      Handler: index.handler
      Runtime: python3.9
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 's3:PutObject'
              Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'
  
  ObjectProcessingFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: lambda/objectprocessing
      Environment:
        Variables:
          DDBTable: !Ref DDBTable
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: 's3:ObjectCreated:*'
      Handler: index.handler
      Runtime: python3.9
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 's3:GetObject'
              Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'
            - Effect: Allow
              Action: 'rekognition:RecognizeCelebrities'
              Resource: '*'
            - Effect: Allow
              Action: 'dynamodb:PutItem'
              Resource: !Sub 'arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DDBTable}'

  DDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: filename
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: filename
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE


# Outputs:
#   set of outputs